//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineMark
{
    using System;
    using System.Collections.Generic;
    
    public partial class headquarters
    {
        public headquarters()
        {
            this.payments = new HashSet<payments>();
            this.programming = new HashSet<programming>();
            this.users = new HashSet<users>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<payments> payments { get; set; }
        public virtual ICollection<programming> programming { get; set; }
        public virtual ICollection<users> users { get; set; }
    }
}
