//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineMark
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_detail
    {
        public int product_id { get; set; }
        public int payment_id { get; set; }
        public int quantity { get; set; }
        public decimal price { get; set; }
    
        public virtual payments payments { get; set; }
        public virtual products products { get; set; }
    }
}
