//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineMark
{
    using System;
    using System.Collections.Generic;
    
    public partial class payments
    {
        public payments()
        {
            this.payment_detail = new HashSet<payment_detail>();
        }
    
        public int id { get; set; }
        public int programming_id { get; set; }
        public int creator_by { get; set; }
        public int headquarter_id { get; set; }
        public string client { get; set; }
        public int quantity { get; set; }
        public decimal price { get; set; }
    
        public virtual headquarters headquarters { get; set; }
        public virtual ICollection<payment_detail> payment_detail { get; set; }
        public virtual users users { get; set; }
        public virtual programming programming { get; set; }
    }
}
