//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineMark
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public products()
        {
            this.payment_detail = new HashSet<payment_detail>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
    
        public virtual ICollection<payment_detail> payment_detail { get; set; }
    }
}
